dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk11
  - openjdk12
#  - openjdk-ea
sudo: false

env: DISPLAY=:99.0

install: true

# install a window manager, needed for SWT-based tests
addons:
  apt:
    packages:
      - metacity

# start metacity window manager before running tests
before_script:
 - sh -e /etc/init.d/xvfb start
 - sleep 5
 - metacity --sm-disable --replace 2> metacity.err &
